In [1]:
import pandas as pd
import numpy as np
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_absolute_error
from sklearn.model_selection import train_test_split

In [2]:
portatiles = pd.read_csv('train.csv')

In [4]:
portatiles.info()

<class 'pandas.DataFrame'>
RangeIndex: 912 entries, 0 to 911
Data columns (total 14 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   id                912 non-null    int64
 1   laptop_ID         912 non-null    int64
 2   Company           912 non-null    str
 3   Product           912 non-null    str
 4   TypeName          912 non-null    str
 5   Inches            912 non-null    float64
 6   ScreenResolution  912 non-null    str
 7   Cpu               912 non-null    str
 8   Ram               912 non-null    str
 9   Memory            912 non-null    str
 10  Gpu               912 non-null    str
 11  OpSys             912 non-null    str
 12  Weight            912 non-null    str
 13  Price_euros       912 non-null    float64
dtypes: float64(2), int64(2), str(10)
memory usage: 99.9 KB

In [3]:
portatiles.head()

,id,laptop_ID,Company,Product,TypeName,Inches,ScreenResolution,Cpu,Ram,Memory,Gpu,OpSys,Weight,Price_euros
0,268,1002,Dell,Inspiron 5567,Notebook,15.6,1366x768,Intel Core i7 7500U 2.7GHz,8GB,1TB HDD,AMD Radeon R7 M445,Windows 10,2.36kg,749.00
1,347,867,Asus,X541NA (N4200/4GB/1TB/W10),Notebook,15.6,1366x768,Intel Pentium Quad Core N4200 1.1GHz,4GB,1TB HDD,Intel HD Graphics 505,Windows 10,2kg,449.00
2,353,966,Toshiba,Portege Z30-C-1CW,Notebook,13.3,Full HD 1920x1080,Intel Core i5 6200U 2.3GHz,8GB,256GB SSD,Intel HD Graphics 520,Windows 7,1.2kg,1460.00
3,578,767,Dell,Alienware 17,Gaming,15.6,IPS Panel 4K Ultra HD 3840x2160,Intel Core i7 7700HQ 2.8GHz,16GB,256GB SSD + 1TB HDD,Nvidia GeForce GTX 1070,Windows 10,4.42kg,2868.99
4,42,1241,Dell,Latitude E7270,Ultrabook,12.5,Full HD / Touchscreen 1920x1080,Intel Core i5 6300U 2.4GHz,8GB,256GB SSD,Intel HD Graphics 520,Windows 7,1.26kg,1713.37

In [5]:
portatiles['Ram'] = portatiles['Ram'].str.replace('GB','').astype(int)
portatiles['Weight'] = portatiles['Weight'].str.replace('kg','').astype(float)

In [6]:
variables = ['Inches', 'Ram', 'Weight']

In [7]:
X = portatiles[variables]
y = portatiles['Price_euros']

In [9]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=11)

In [11]:
from sklearn.linear_model import LinearRegression

modelo = LinearRegression()
modelo.fit(X_train, y_train)

print(f'MAE: {mean_absolute_error(y_test, modelo.predict(X_test))}')

MAE: 370.83940631464685

In [12]:
from sklearn.tree import DecisionTreeRegressor

modelo = DecisionTreeRegressor(random_state=11)
modelo.fit(X_train, y_train)

print(f'MAE: {mean_absolute_error(y_test, modelo.predict(X_test)):.2f}')

MAE: 328.73

In [15]:
import pickle

pickle.dump(modelo, open('modelo_v1.pkl', 'wb'))

In [13]:
# cargo el archivo sin precios
test = pd.read_csv('test.csv')
# limpio las columnas de Ram y Weight
test['Ram'] = test['Ram'].str.replace('GB','').astype(int)
test['Weight'] = test['Weight'].str.replace('kg','').astype(float)
# cargo el ejemplo de submission
submission = pd.read_csv('sample_submission.csv')
# hago las predicciones
submission['Price_euros'] = modelo.predict(test[variables])
# enseño las primeras filas de la solución
submission.head()

     id  Price_euros
0  1014  1499.000000
1   845   801.874667
2  1151   386.950000
3  1265  1484.500000
4   573  1126.880000

In [14]:
# guardo el archivo de submission
submission.to_csv('submission1.csv', index=False)